# Generated by Django 2.1.2 on 2019-07-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_auto_20190706_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Full_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='Phone_Number',
            new_name='number',
        ),
    ]
